export interface Slide {
  id: string;
  imageUrl: string;
  wakeupWord: string; // The phrase that triggers this slide
  transition: TransitionEffect;
  name: string; // User friendly name
}

export enum TransitionEffect {
  NONE = 'none',
  // Original List
  ACCORDION = 'effect-accordion',
  AIRPLANE = 'effect-airplane',
  BARS = 'effect-bars',
  BLEND = 'effect-blend',
  BLINDS = 'effect-blinds',
  BOUNCE = 'effect-bounce',
  BOUNCY_DOTS = 'effect-bouncy-dots',
  BOX = 'effect-box',
  CHECKERBOARD = 'effect-checkerboard',
  CIRCLES = 'effect-circles',
  CLOCK = 'effect-clock',
  COMB = 'effect-comb',
  CONVEYOR = 'effect-conveyor',
  COVER = 'effect-cover',
  CUBE = 'effect-cube',
  CUT = 'effect-cut',
  DIAMOND = 'effect-diamond',
  DISSOLVE = 'effect-dissolve',
  FINE_DUST = 'effect-fine-dust',
  FADE = 'effect-fade',
  FALLING_CONFETTI = 'effect-falling-confetti',
  FERRIS_WHEEL = 'effect-ferris-wheel',
  FLASH = 'effect-flash',
  FLIP = 'effect-flip',
  FRACTURE = 'effect-fracture',
  GALLERY = 'effect-gallery',
  GLITTER = 'effect-glitter',
  HELIX = 'effect-helix',
  HONEYCOMB = 'effect-honeycomb',
  IRIS = 'effect-iris',
  LENS_FLARE = 'effect-lens-flare',
  MORPH = 'effect-morph',
  ORIGAMI = 'effect-origami',
  PAGES = 'effect-pages',
  PAN = 'effect-pan',
  PEEL_OFF = 'effect-peel-off',
  PIXELATE = 'effect-pixelate',
  PINWHEEL = 'effect-pinwheel',
  PULSE = 'effect-pulse',
  PUSH = 'effect-push',
  REVEAL = 'effect-reveal',
  ROTATE = 'effect-rotate',
  SHRED = 'effect-shred',
  SHUFFLE = 'effect-shuffle',
  SPARKLE = 'effect-sparkle',
  SPIRAL = 'effect-spiral',
  SPOTLIGHT = 'effect-spotlight',
  SPLIT = 'effect-split',
  STAIRS = 'effect-stairs',
  TILES = 'effect-tiles',
  TURBULENCE = 'effect-turbulence',
  UNCOVER = 'effect-uncover',
  VORTEX = 'effect-vortex',
  WEDGE = 'effect-wedge',
  WHEELBARROW = 'effect-wheelbarrow',
  WINDOW = 'effect-window',
  WIPE = 'effect-wipe',
  ZOOM = 'effect-zoom',

  // 3D Effects (Advanced)
  ARRIVE = 'effect-arrive',
  LEAVE = 'effect-leave',
  TURNTABLE = 'effect-turntable',
  SWING = 'effect-swing',
  JUMP_TURN = 'effect-jump-turn',
  ROTATE_3D = 'effect-rotate-3d',
  ORBIT_3D = 'effect-orbit-3d',
  PAN_3D = 'effect-pan-3d',
  SPIN_3D = 'effect-spin-3d',
  TILT_3D = 'effect-tilt-3d',

  // Classic Effects
  NEWSFLASH = 'effect-newsflash',
  OUTLINE = 'effect-outline',
  UNCOVER_LEFT = 'effect-uncover-left',
  UNCOVER_RIGHT = 'effect-uncover-right',
  UNCOVER_UP = 'effect-uncover-up',
  UNCOVER_DOWN = 'effect-uncover-down',
  WEDGE_LEFT = 'effect-wedge-left',
  WEDGE_RIGHT = 'effect-wedge-right',
  BLINDS_LEFT = 'effect-blinds-left',
  BLINDS_RIGHT = 'effect-blinds-right',
  BLINDS_UP = 'effect-blinds-up',
  BLINDS_DOWN = 'effect-blinds-down',
  COMB_HORIZONTAL = 'effect-comb-horizontal',
  COMB_VERTICAL = 'effect-comb-vertical',
  PAN_UP = 'effect-pan-up',
  PAN_DOWN = 'effect-pan-down',
  PAN_LEFT = 'effect-pan-left',
  PAN_RIGHT = 'effect-pan-right',
  PLUS = 'effect-plus',
  ADVANCE = 'effect-advance',
  SHRINK = 'effect-shrink',
  EXPAND = 'effect-expand',
  COLLAPSE = 'effect-collapse',
  STRETCH = 'effect-stretch',
  SQUEEZE = 'effect-squeeze',
  WHIP = 'effect-whip',
  RIPPLE = 'effect-ripple',
  GLIDE = 'effect-glide',

  // Smooth / Animated
  FADE_THROUGH_BLACK = 'effect-fade-black',
  FADE_THROUGH_WHITE = 'effect-fade-white',
  DRIFT = 'effect-drift',
  CRUSH = 'effect-crush',
  GRIND = 'effect-grind',
  EMBOSS = 'effect-emboss',
  SHALLOW = 'effect-shallow',
  DEPTH = 'effect-depth',
  REFLOW = 'effect-reflow',
  PUSH_UP = 'effect-push-up',
  PUSH_DOWN = 'effect-push-down',
  PUSH_LEFT = 'effect-push-left',
  PUSH_RIGHT = 'effect-push-right',
  SIPHON = 'effect-siphon',
  SWIVEL = 'effect-swivel',
  TUMBLE = 'effect-tumble',
  CASCADE = 'effect-cascade',
  WAVE = 'effect-wave',
  CLOUD = 'effect-cloud',
  SHIMMER = 'effect-shimmer',
  GLIMMER = 'effect-glimmer',
  FLICKER = 'effect-flicker',
  PULSE_LIGHT = 'effect-pulse-light',
  PULSE_DARK = 'effect-pulse-dark',
  STROBE = 'effect-strobe',
  SWIRL = 'effect-swirl',
  TWIRL = 'effect-twirl',
  // Spiral already exists
  HOP = 'effect-hop',
  SKIP = 'effect-skip',
  JUMP = 'effect-jump',
  FLOAT = 'effect-float',
  BOUNCE_LEFT = 'effect-bounce-left',
  BOUNCE_RIGHT = 'effect-bounce-right',
  BOUNCE_UP = 'effect-bounce-up',
  BOUNCE_DOWN = 'effect-bounce-down',
  SPRING = 'effect-spring',
  SWAY = 'effect-sway',
  PENDULUM = 'effect-pendulum',
  ROCK = 'effect-rock',
  FLOAT_UP = 'effect-float-up',
  FLOAT_DOWN = 'effect-float-down',
  FLOAT_LEFT = 'effect-float-left',
  FLOAT_RIGHT = 'effect-float-right',
  SMOOTH_STEP = 'effect-smooth-step',
  EASE_IN = 'effect-ease-in',
  EASE_OUT = 'effect-ease-out',
  EASE_IN_OUT = 'effect-ease-in-out',
  DECELERATE = 'effect-decelerate',
  ACCELERATE = 'effect-accelerate',

  // Advanced 3D Morph
  MORPH_3D_ROTATE = 'effect-morph-3d-rotate',
  MORPH_3D_FLIP = 'effect-morph-3d-flip',
  MORPH_3D_SPIN = 'effect-morph-3d-spin',
  MORPH_3D_EXPAND = 'effect-morph-3d-expand',
  MORPH_3D_COMPRESS = 'effect-morph-3d-compress',
  MORPH_OBJECT = 'effect-morph-object',
  MORPH_POSITION = 'effect-morph-position',
  MORPH_SIZE = 'effect-morph-size',
  MORPH_COLOR = 'effect-morph-color',

  // Premium / Specialty
  PLANE = 'effect-plane',
  PLANE_LEFT = 'effect-plane-left',
  PLANE_RIGHT = 'effect-plane-right',
  PLANE_UP = 'effect-plane-up',
  PLANE_DOWN = 'effect-plane-down',
  PLANE_DIAGONAL = 'effect-plane-diagonal',
  HELIX_LEFT = 'effect-helix-left',
  HELIX_RIGHT = 'effect-helix-right',
  TETRAHEDRON = 'effect-tetrahedron',
  OCTAHEDRON = 'effect-octahedron',
  ICOSAHEDRON = 'effect-icosahedron',
  GEOMETRIC_SPIN = 'effect-geometric-spin',
  QUANTUM = 'effect-quantum',
  PRISM_ROTATE = 'effect-prism-rotate',
}

export interface SubtitleState {
  original: string;
  translated: string;
  isTranslating: boolean;
}

export interface AppState {
  slides: Slide[];
  isPresentationMode: boolean;
  currentSlideIndex: number | -1; // -1 indicates blank/start screen
  blankScreenWakeupWord: string;
  subtitleLanguage: string; // e.g., 'te-IN' for Telugu
}

// Alphabetical list for the UI
export const TRANSITIONS = [
  // Original
  { id: TransitionEffect.NONE, label: 'None (Instant)' },
  { id: TransitionEffect.ACCORDION, label: 'Accordion' },
  { id: TransitionEffect.AIRPLANE, label: 'Airplane' },
  { id: TransitionEffect.BARS, label: 'Bars' },
  { id: TransitionEffect.BLEND, label: 'Blend' },
  { id: TransitionEffect.BLINDS, label: 'Blinds' },
  { id: TransitionEffect.BOUNCE, label: 'Bounce' },
  { id: TransitionEffect.BOUNCY_DOTS, label: 'Bouncy Dots' },
  { id: TransitionEffect.BOX, label: 'Box' },
  { id: TransitionEffect.CHECKERBOARD, label: 'Checkerboard' },
  { id: TransitionEffect.CIRCLES, label: 'Circles' },
  { id: TransitionEffect.CLOCK, label: 'Clock' },
  { id: TransitionEffect.COMB, label: 'Comb' },
  { id: TransitionEffect.CONVEYOR, label: 'Conveyor' },
  { id: TransitionEffect.COVER, label: 'Cover' },
  { id: TransitionEffect.CUBE, label: 'Cube' },
  { id: TransitionEffect.CUT, label: 'Cut' },
  { id: TransitionEffect.DIAMOND, label: 'Diamond' },
  { id: TransitionEffect.DISSOLVE, label: 'Dissolve' },
  { id: TransitionEffect.FADE, label: 'Fade' },
  { id: TransitionEffect.FALLING_CONFETTI, label: 'Falling Confetti' },
  { id: TransitionEffect.FERRIS_WHEEL, label: 'Ferris Wheel' },
  { id: TransitionEffect.FINE_DUST, label: 'Fine Dust' },
  { id: TransitionEffect.FLASH, label: 'Flash' },
  { id: TransitionEffect.FLIP, label: 'Flip' },
  { id: TransitionEffect.FRACTURE, label: 'Fracture' },
  { id: TransitionEffect.GALLERY, label: 'Gallery' },
  { id: TransitionEffect.GLITTER, label: 'Glitter' },
  { id: TransitionEffect.HELIX, label: 'Helix' },
  { id: TransitionEffect.HONEYCOMB, label: 'Honeycomb' },
  { id: TransitionEffect.IRIS, label: 'Iris' },
  { id: TransitionEffect.LENS_FLARE, label: 'Lens Flare' },
  { id: TransitionEffect.MORPH, label: 'Morph' },
  { id: TransitionEffect.ORIGAMI, label: 'Origami' },
  { id: TransitionEffect.PAGES, label: 'Pages' },
  { id: TransitionEffect.PAN, label: 'Pan' },
  { id: TransitionEffect.PEEL_OFF, label: 'Peel Off' },
  { id: TransitionEffect.PIXELATE, label: 'Pixelate' },
  { id: TransitionEffect.PINWHEEL, label: 'Pinwheel' },
  { id: TransitionEffect.PULSE, label: 'Pulse' },
  { id: TransitionEffect.PUSH, label: 'Push' },
  { id: TransitionEffect.REVEAL, label: 'Reveal' },
  { id: TransitionEffect.ROTATE, label: 'Rotate' },
  { id: TransitionEffect.SHRED, label: 'Shred' },
  { id: TransitionEffect.SHUFFLE, label: 'Shuffle' },
  { id: TransitionEffect.SPARKLE, label: 'Sparkle' },
  { id: TransitionEffect.SPIRAL, label: 'Spiral' },
  { id: TransitionEffect.SPLIT, label: 'Split' },
  { id: TransitionEffect.SPOTLIGHT, label: 'Spotlight' },
  { id: TransitionEffect.STAIRS, label: 'Stairs' },
  { id: TransitionEffect.TILES, label: 'Tiles' },
  { id: TransitionEffect.TURBULENCE, label: 'Turbulence' },
  { id: TransitionEffect.UNCOVER, label: 'Uncover' },
  { id: TransitionEffect.VORTEX, label: 'Vortex' },
  { id: TransitionEffect.WEDGE, label: 'Wedge' },
  { id: TransitionEffect.WHEELBARROW, label: 'Wheelbarrow' },
  { id: TransitionEffect.WINDOW, label: 'Window' },
  { id: TransitionEffect.WIPE, label: 'Wipe' },
  { id: TransitionEffect.ZOOM, label: 'Zoom' },

  // New Additions
  { id: TransitionEffect.ARRIVE, label: 'Arrive (3D)' },
  { id: TransitionEffect.LEAVE, label: 'Leave (3D)' },
  { id: TransitionEffect.TURNTABLE, label: 'Turntable' },
  { id: TransitionEffect.SWING, label: 'Swing' },
  { id: TransitionEffect.JUMP_TURN, label: 'Jump & Turn' },
  { id: TransitionEffect.ROTATE_3D, label: 'Rotate 3D' },
  { id: TransitionEffect.ORBIT_3D, label: 'Orbit 3D' },
  { id: TransitionEffect.PAN_3D, label: 'Pan 3D' },
  { id: TransitionEffect.SPIN_3D, label: 'Spin 3D' },
  { id: TransitionEffect.TILT_3D, label: 'Tilt 3D' },
  
  { id: TransitionEffect.NEWSFLASH, label: 'Newsflash' },
  { id: TransitionEffect.OUTLINE, label: 'Outline' },
  { id: TransitionEffect.UNCOVER_LEFT, label: 'Uncover Left' },
  { id: TransitionEffect.UNCOVER_RIGHT, label: 'Uncover Right' },
  { id: TransitionEffect.UNCOVER_UP, label: 'Uncover Up' },
  { id: TransitionEffect.UNCOVER_DOWN, label: 'Uncover Down' },
  { id: TransitionEffect.WEDGE_LEFT, label: 'Wedge Left' },
  { id: TransitionEffect.WEDGE_RIGHT, label: 'Wedge Right' },
  { id: TransitionEffect.BLINDS_LEFT, label: 'Blinds Left' },
  { id: TransitionEffect.BLINDS_RIGHT, label: 'Blinds Right' },
  { id: TransitionEffect.BLINDS_UP, label: 'Blinds Up' },
  { id: TransitionEffect.BLINDS_DOWN, label: 'Blinds Down' },
  { id: TransitionEffect.COMB_HORIZONTAL, label: 'Comb Horizontal' },
  { id: TransitionEffect.COMB_VERTICAL, label: 'Comb Vertical' },
  { id: TransitionEffect.PAN_UP, label: 'Pan Up' },
  { id: TransitionEffect.PAN_DOWN, label: 'Pan Down' },
  { id: TransitionEffect.PAN_LEFT, label: 'Pan Left' },
  { id: TransitionEffect.PAN_RIGHT, label: 'Pan Right' },
  { id: TransitionEffect.PLUS, label: 'Plus' },
  { id: TransitionEffect.ADVANCE, label: 'Advance' },
  { id: TransitionEffect.SHRINK, label: 'Shrink' },
  { id: TransitionEffect.EXPAND, label: 'Expand' },
  { id: TransitionEffect.COLLAPSE, label: 'Collapse' },
  { id: TransitionEffect.STRETCH, label: 'Stretch' },
  { id: TransitionEffect.SQUEEZE, label: 'Squeeze' },
  { id: TransitionEffect.WHIP, label: 'Whip' },
  { id: TransitionEffect.RIPPLE, label: 'Ripple' },
  { id: TransitionEffect.GLIDE, label: 'Glide' },
  
  { id: TransitionEffect.FADE_THROUGH_BLACK, label: 'Fade Through Black' },
  { id: TransitionEffect.FADE_THROUGH_WHITE, label: 'Fade Through White' },
  { id: TransitionEffect.DRIFT, label: 'Drift' },
  { id: TransitionEffect.CRUSH, label: 'Crush' },
  { id: TransitionEffect.GRIND, label: 'Grind' },
  { id: TransitionEffect.EMBOSS, label: 'Emboss' },
  { id: TransitionEffect.SHALLOW, label: 'Shallow' },
  { id: TransitionEffect.DEPTH, label: 'Depth' },
  { id: TransitionEffect.REFLOW, label: 'Reflow' },
  { id: TransitionEffect.PUSH_UP, label: 'Push Up' },
  { id: TransitionEffect.PUSH_DOWN, label: 'Push Down' },
  { id: TransitionEffect.PUSH_LEFT, label: 'Push Left' },
  { id: TransitionEffect.PUSH_RIGHT, label: 'Push Right' },
  { id: TransitionEffect.SIPHON, label: 'Siphon' },
  { id: TransitionEffect.SWIVEL, label: 'Swivel' },
  { id: TransitionEffect.TUMBLE, label: 'Tumble' },
  { id: TransitionEffect.CASCADE, label: 'Cascade' },
  { id: TransitionEffect.WAVE, label: 'Wave' },
  { id: TransitionEffect.CLOUD, label: 'Cloud' },
  { id: TransitionEffect.SHIMMER, label: 'Shimmer' },
  { id: TransitionEffect.GLIMMER, label: 'Glimmer' },
  { id: TransitionEffect.FLICKER, label: 'Flicker' },
  { id: TransitionEffect.PULSE_LIGHT, label: 'Pulse Light' },
  { id: TransitionEffect.PULSE_DARK, label: 'Pulse Dark' },
  { id: TransitionEffect.STROBE, label: 'Strobe' },
  { id: TransitionEffect.SWIRL, label: 'Swirl' },
  { id: TransitionEffect.TWIRL, label: 'Twirl' },
  { id: TransitionEffect.HOP, label: 'Hop' },
  { id: TransitionEffect.SKIP, label: 'Skip' },
  { id: TransitionEffect.JUMP, label: 'Jump' },
  { id: TransitionEffect.FLOAT, label: 'Float' },
  { id: TransitionEffect.BOUNCE_LEFT, label: 'Bounce Left' },
  { id: TransitionEffect.BOUNCE_RIGHT, label: 'Bounce Right' },
  { id: TransitionEffect.BOUNCE_UP, label: 'Bounce Up' },
  { id: TransitionEffect.BOUNCE_DOWN, label: 'Bounce Down' },
  { id: TransitionEffect.SPRING, label: 'Spring' },
  { id: TransitionEffect.SWAY, label: 'Sway' },
  { id: TransitionEffect.PENDULUM, label: 'Pendulum' },
  { id: TransitionEffect.ROCK, label: 'Rock' },
  { id: TransitionEffect.FLOAT_UP, label: 'Float Up' },
  { id: TransitionEffect.FLOAT_DOWN, label: 'Float Down' },
  { id: TransitionEffect.FLOAT_LEFT, label: 'Float Left' },
  { id: TransitionEffect.FLOAT_RIGHT, label: 'Float Right' },
  { id: TransitionEffect.SMOOTH_STEP, label: 'Smooth Step' },
  { id: TransitionEffect.EASE_IN, label: 'Ease In' },
  { id: TransitionEffect.EASE_OUT, label: 'Ease Out' },
  { id: TransitionEffect.EASE_IN_OUT, label: 'Ease In Out' },
  { id: TransitionEffect.DECELERATE, label: 'Decelerate' },
  { id: TransitionEffect.ACCELERATE, label: 'Accelerate' },
  
  { id: TransitionEffect.MORPH_3D_ROTATE, label: 'Morph 3D Rotate' },
  { id: TransitionEffect.MORPH_3D_FLIP, label: 'Morph 3D Flip' },
  { id: TransitionEffect.MORPH_3D_SPIN, label: 'Morph 3D Spin' },
  { id: TransitionEffect.MORPH_3D_EXPAND, label: 'Morph 3D Expand' },
  { id: TransitionEffect.MORPH_3D_COMPRESS, label: 'Morph 3D Compress' },
  { id: TransitionEffect.MORPH_OBJECT, label: 'Morph Object' },
  { id: TransitionEffect.MORPH_POSITION, label: 'Morph Position' },
  { id: TransitionEffect.MORPH_SIZE, label: 'Morph Size' },
  { id: TransitionEffect.MORPH_COLOR, label: 'Morph Color' },
  
  { id: TransitionEffect.PLANE, label: 'Plane' },
  { id: TransitionEffect.PLANE_LEFT, label: 'Plane Left' },
  { id: TransitionEffect.PLANE_RIGHT, label: 'Plane Right' },
  { id: TransitionEffect.PLANE_UP, label: 'Plane Up' },
  { id: TransitionEffect.PLANE_DOWN, label: 'Plane Down' },
  { id: TransitionEffect.PLANE_DIAGONAL, label: 'Plane Diagonal' },
  { id: TransitionEffect.HELIX_LEFT, label: 'Helix Left' },
  { id: TransitionEffect.HELIX_RIGHT, label: 'Helix Right' },
  { id: TransitionEffect.TETRAHEDRON, label: 'Tetrahedron' },
  { id: TransitionEffect.OCTAHEDRON, label: 'Octahedron' },
  { id: TransitionEffect.ICOSAHEDRON, label: 'Icosahedron' },
  { id: TransitionEffect.GEOMETRIC_SPIN, label: 'Geometric Spin' },
  { id: TransitionEffect.QUANTUM, label: 'Quantum' },
  { id: TransitionEffect.PRISM_ROTATE, label: 'Prism Rotate' },
].sort((a, b) => a.label.localeCompare(b.label)); // Alphabetical Sort